// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-q4x2nJ0E9VqDHvtF7Ne2Vxn_1GRhzDQ',
    appId: '1:824379492369:web:34ac145a73b3dc6c9f89b0',
    messagingSenderId: '824379492369',
    projectId: 'multitenant-lms',
    authDomain: 'multitenant-lms.firebaseapp.com',
    storageBucket: 'multitenant-lms.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlZAegx-38ihkyOxSLU1vOEHpPHwPs3O0',
    appId: '1:824379492369:android:1222e0336dae5a7e9f89b0',
    messagingSenderId: '824379492369',
    projectId: 'multitenant-lms',
    storageBucket: 'multitenant-lms.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3sID3lzScwVnFra_6wyVVcssSqmkxi0A',
    appId: '1:824379492369:ios:de9e74ac0571a3b09f89b0',
    messagingSenderId: '824379492369',
    projectId: 'multitenant-lms',
    storageBucket: 'multitenant-lms.firebasestorage.app',
    iosBundleId: 'com.devcohort.devcohortLms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3sID3lzScwVnFra_6wyVVcssSqmkxi0A',
    appId: '1:824379492369:ios:de9e74ac0571a3b09f89b0',
    messagingSenderId: '824379492369',
    projectId: 'multitenant-lms',
    storageBucket: 'multitenant-lms.firebasestorage.app',
    iosBundleId: 'com.devcohort.devcohortLms',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-q4x2nJ0E9VqDHvtF7Ne2Vxn_1GRhzDQ',
    appId: '1:824379492369:web:bb3a71a97540db0a9f89b0',
    messagingSenderId: '824379492369',
    projectId: 'multitenant-lms',
    authDomain: 'multitenant-lms.firebaseapp.com',
    storageBucket: 'multitenant-lms.firebasestorage.app',
  );
}
